#!/usr/bin/env python
#
#    Copyright (c) 2016 Timothy Savannah All Rights Reserved
#  under terms of the GPL version 2. You should have recieved a copy of this with distribution,
#  as LICENSE. You may also find the full text at https://github.com/kata198/popLines/LICENSE
#

#  This program turns files into queues. You can pop off random elements within a given file
#   So your file can contain a list of items to process, and you can use this to pop off that queue.

#vim: set ts=4 sw=4 expandtab
import os
import sys

from PopLines import popRandom

def printUsage():
    sys.stderr.write('''Usage: popRandom [number of lines] [filename]

Removes the given number of lines from a random selection within the provided file, returning on stdout.

Use this program to turn a list into a queue.
''')

if __name__ == '__main__':

    if '--help' in sys.argv:
        printUsage()
        sys.exit(1)

    args = sys.argv[1:]

    if len(args) != 2:
        sys.stderr.write('Wrong number of arguments.\n\n')
        printUsage()
        sys.exit(1)

    numLines = args[0]
    if not numLines.isdigit():
        sys.stderr.write('Number of lines (second argument) must be an integer.\n\n')
        printUsage()
        sys.exit(1)

    numLines = int(numLines)

    filename = args[1]
    if not os.path.exists(filename):
        sys.stderr.write('No such file: %s\n' %(filename,))
        sys.exit(2)
    if not os.path.isfile(filename):
        sys.stderr.write('Not a file: %s\n' %(filename,))
        sys.exit(2)

    try:
        output = popRandom(numLines, filename)
    except Exception as e:
        sys.stderr.write('Error: %s\n' %(str(e,)))
        raise e
        sys.exit(2)

    if len(output) > 0:
        sys.stdout.write('\n'.join(output))
        sys.stdout.write('\n')

